import Character from "../Character";
import { RIME_SPELLS, RimeSpellNames } from "./rime.spells";

export type RimeOptions = {
  stamina: number;
  intellect: number;
  crit: number;
  expertise: number;
  haste: number;
};

export class Rime extends Character {
  static readonly MAX_ANIMA = 10;
  static readonly MAX_WINTER_ORB = 5;

  anima: number;
  winterOrb: number;

  constructor(options: RimeOptions) {
    super({
      name: "Rime",
      baseHealth: 3907,
      baseCrit: 5,
      stamina: options.stamina,
      intellect: options.intellect,
      crit: options.crit,
      expertise: options.expertise,
      haste: options.haste,
    });
    this.anima = 0;
    this.winterOrb = 0;

    this.spells = RIME_SPELLS;
  }

  /**
   * Anima is a resource that is generated by casting spells.
   * When Anima reaches 10, it resets to 0 and generates a Winter Orb.
   * Winter Orbs are used to cast powerful spells.
   * @param amount - Amount of Anima to generate
   */
  generateAnima(amount: number): void {
    this.anima += amount;
    if (this.anima >= Rime.MAX_ANIMA) {
      this.anima = 0;
      this.triggerAnimaSpike(3);
      if (this.winterOrb < Rime.MAX_WINTER_ORB) {
        this.winterOrb++;
        console.log("Winter Orb generated");
      }
    }
  }

  /**
   * Anima Spike is a spell that deals damage based on the amount of Anima generated.
   * @param amount - Amount of Anima generated
   */
  triggerAnimaSpike(amount: number): void {
    const animaSpike = this.getSpell(RimeSpellNames.ANIMA_SPIKE);
    if (!animaSpike) return;
    for (let i = 0; i < amount; i++) {
      animaSpike.cast(this);
    }
  }

  /**
   * Winter Orb is a resource that is generated by Anima and consumed by powerful spells.
   * @param amount The amount of Winter Orbs gained or consumed
   * @returns
   */
  updateWinterOrb(amount: number): void {
    if (amount === 0) return;

    // Can't go above max winter orbs
    if (this.winterOrb + amount > Rime.MAX_WINTER_ORB) {
      console.log("Winter Orb is full");
      this.winterOrb = Rime.MAX_WINTER_ORB;
      return;
    }

    // If not enough orbs, do nothing
    if (this.winterOrb + amount < 0) {
      console.log("Not enough Winter Orbs");
      return;
    }

    this.winterOrb += amount;
    console.log(`Winter Orb ${amount > 0 ? "generated" : "consumed"}`);
  }
}
